services:
  - type: web
    name: facebook-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && PLAYWRIGHT_BROWSERS_PATH=./playwright-browsers node node_modules/playwright/cli.js install chromium
    startCommand: npm start
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/playwright-browsers
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
